spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: "update"

  datasource:
    url: "jdbc:mysql://localhost:3306/beer_service"
    username: "guest"
    password: "guest"
